#!/usr/bin/env python3
"""Pack web/index.html into index_html.h (minified + gzipped PROGMEM array).

Run from anywhere after editing the UI:   python tools/build_web.py
Uses only the Python standard library.
"""
import gzip
import hashlib
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "web" / "index.html"
OUT = ROOT / "index_html.h"


def minify(s: str) -> str:
    s = re.sub(r"<!--.*?-->", "", s, flags=re.S)
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    lines = []
    for line in s.splitlines():
        t = line.strip()
        # Newlines are kept so JS automatic semicolon insertion stays safe.
        if t and not t.startswith("//"):
            lines.append(t)
    return "\n".join(lines)


def main() -> None:
    raw = SRC.read_text(encoding="utf-8")
    html = minify(raw).encode("utf-8")
    gz = gzip.compress(html, compresslevel=9, mtime=0)
    etag = hashlib.sha1(gz).hexdigest()[:10]

    rows = []
    for i in range(0, len(gz), 20):
        rows.append("  " + ",".join(f"0x{b:02x}" for b in gz[i:i + 20]) + ",")

    OUT.write_text(
        "// AUTO-GENERATED by tools/build_web.py from web/index.html - do not edit.\n"
        "#pragma once\n"
        "#include <Arduino.h>\n\n"
        f'#define INDEX_HTML_ETAG "\\"{etag}\\""\n'
        f"static const size_t INDEX_HTML_GZ_LEN = {len(gz)};\n"
        "static const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n"
        + "\n".join(rows)
        + "\n};\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"{SRC.name}: {len(raw.encode())} B -> minified {len(html)} B -> gzip {len(gz)} B  (etag {etag})")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
